//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {Device} from './device';
import {DeviceService} from './device.service';
import {Account} from '../account/account';

@Component({
    moduleId: module.id,
	templateUrl: 'device-detail.component.html',
	selector: 'device-detail',
})
export class DeviceDetailComponent implements OnInit, OnDestroy {
    device : Device;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new Device
    set accountFk(accountFk : Account) {
        this.device = new Device();
        this.device.accountFk = accountFk;
    }

    @Output() onSaveClicked = new EventEmitter<Device>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private deviceService: DeviceService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for device-detail ' + id);

            if (id === 'new') {
                this.device = new Device();
            } else {
                this.deviceService.getDevice(id)
                    .subscribe(device => {
                            this.device = device;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoAccountFk() {
        this.router.navigate(['/account', this.device.accountFk.id]);
    }

    clearAccountFk() {
        this.device.accountFk = null;
    }

    onSave() {
        this.deviceService.update(this.device).
            subscribe(
                device => {
                    this.device = device;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.device);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
