//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { Device } from './device';
import { DeviceDetailComponent } from './device-detail.component';
import { DeviceService } from './device.service';
import { Account } from '../account/account';
import { AccountLineComponent } from '../account/account-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'device-list.component.html',
	selector: 'device-list'
})
export class DeviceListComponent {

    @Input() header = "Devices...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    deviceToDelete : Device;

    // basic search criterias (visible if not in 'sub' mode)
    example : Device = new Device();

    // list is paginated
    currentPage : PageResponse<Device> = new PageResponse<Device>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _accountFk : Account;

    constructor(private router : Router,
        private deviceService : DeviceService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.deviceService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set accountFk(accountFk : Account) {
        if (accountFk == null) {
            return;
        }
        this._accountFk = accountFk;

        this.example = new Device();
        this.example.accountFk = new Account();
        this.example.accountFk.id = this._accountFk.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/device', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/device', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let deviceToDelete : Device = <Device> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(deviceToDelete);
            }
        });
    }

    private delete(deviceToDelete : Device) {
        let id =  deviceToDelete.id;

        this.deviceService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(deviceToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}