/*
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.bpe.monitor.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.bpe.monitor.domain.AlarmRule;
import com.bpe.monitor.domain.AlarmRule_;

public interface AlarmRuleRepository extends JpaRepository<AlarmRule, Long> {

    default List<AlarmRule> complete(String query, int maxResults) {
        AlarmRule probe = new AlarmRule();
        probe.setEmailToAlert(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(AlarmRule_.emailToAlert.getName(), match -> match.ignoreCase().startsWith());

        Page<AlarmRule> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}