/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.mycompany.myapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.mycompany.myapp.domain.Author;
import com.mycompany.myapp.domain.Author_;

public interface AuthorRepository extends JpaRepository<Author, Integer> {

    default List<Author> complete(String query, int maxResults) {
        Author probe = new Author();
        probe.setFirstName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(Author_.firstName.getName(), match -> match.ignoreCase().startsWith());

        Page<Author> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}