/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.LocalDate;
import java.time.LocalDateTime;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mycompany.myapp.domain.Civility;

/**
 * Simple DTO for Author.
 */
public class AuthorDTO {
    public Integer id;
    public Civility civility;
    public String firstName;
    public String lastName;
    public String email;
    public LocalDate birthDate;
    public LocalDateTime birthDateTime;
    public AuthorDTO favoriteAuthor;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}