/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.math.BigDecimal;
import java.time.LocalDate;

import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Simple DTO for Book.
 */
public class BookDTO {
    public Integer id;
    public String title;
    public String summary;
    public String extractFileName;
    public String extractContentType;
    public Long extractSize;
    public LocalDate publicationDate;
    public Boolean bestSeller;
    public BigDecimal price;
    public AuthorDTO author;
    public AuthorDTO coAuthor;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}