/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mycompany.myapp.domain.UseCase3Pk;

/**
 * Simple DTO for UseCase3.
 */
public class UseCase3DTO {
    // Composite primary key
    public UseCase3Pk id;
    public String dummy;
    public UseCase2DTO id2;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null && id.areFieldsSet();
    }
}