/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mycompany.myapp.domain.UseCase1Pk;

/**
 * Simple DTO for UseCase1.
 */
public class UseCase1DTO {
    // Composite primary key
    public UseCase1Pk id;
    public String dummy;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null && id.areFieldsSet();
    }
}