/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/dto/EntityDTO.java.e.vm
 */
package com.mycompany.myapp.dto;

import java.time.Instant;
import java.util.List;

import com.fasterxml.jackson.annotation.JsonIgnore;
import com.mycompany.myapp.domain.Civility;
import com.mycompany.myapp.domain.CountryCode;

/**
 * Simple DTO for User.
 */
public class UserDTO {
    public Integer id;
    public String login;
    public String password;
    public String email;
    public Boolean isEnabled;
    public Civility civility;
    public CountryCode countryCode;
    public String firstName;
    public String lastName;
    public Instant creationDate;
    public String creationAuthor;
    public Instant lastModificationDate;
    public String lastModificationAuthor;
    public Integer version;
    public PassportDTO passport;;
    public List<RoleDTO> roles;

    @JsonIgnore
    public boolean isIdSet() {
        return id != null;
    }
}