/*
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.mycompany.myapp.domain;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "device")
public class Device implements Identifiable<Long>, Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Device.class.getName());

    // Raw attributes
    private Long id;
    private String description;
    private Float heightAboveSeaLevel;
    private Float lat;
    private Float longitue;
    private String name;

    // Many to one
    private Account accountFk;

    @Override
    public String entityClassName() {
        return Device.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Override
    @Column(name = "id", precision = 19)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Long getId() {
        return id;
    }

    @Override
    public void setId(Long id) {
        this.id = id;
    }

    public Device id(Long id) {
        setId(id);
        return this;
    }

    @Override
    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [description] ------------------------

    @NotEmpty
    @Size(max = 40)
    @Column(name = "description", nullable = false, length = 40)
    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public Device description(String description) {
        setDescription(description);
        return this;
    }
    // -- [heightAboveSeaLevel] ------------------------

    @Digits(integer = 12, fraction = 0)
    @Column(name = "height_above_sea_level", precision = 12)
    public Float getHeightAboveSeaLevel() {
        return heightAboveSeaLevel;
    }

    public void setHeightAboveSeaLevel(Float heightAboveSeaLevel) {
        this.heightAboveSeaLevel = heightAboveSeaLevel;
    }

    public Device heightAboveSeaLevel(Float heightAboveSeaLevel) {
        setHeightAboveSeaLevel(heightAboveSeaLevel);
        return this;
    }
    // -- [lat] ------------------------

    @Digits(integer = 12, fraction = 0)
    @Column(name = "lat", precision = 12)
    public Float getLat() {
        return lat;
    }

    public void setLat(Float lat) {
        this.lat = lat;
    }

    public Device lat(Float lat) {
        setLat(lat);
        return this;
    }
    // -- [longitue] ------------------------

    @Digits(integer = 12, fraction = 0)
    @Column(name = "longitue", precision = 12)
    public Float getLongitue() {
        return longitue;
    }

    public void setLongitue(Float longitue) {
        this.longitue = longitue;
    }

    public Device longitue(Float longitue) {
        setLongitue(longitue);
        return this;
    }
    // -- [name] ------------------------

    @NotEmpty
    @Size(max = 15)
    @Column(name = "name", nullable = false, length = 15)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Device name(String name) {
        setName(name);
        return this;
    }

    // -----------------------------------------------------------------
    // Many to One support
    // -----------------------------------------------------------------

    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
    // many-to-one: Device.accountFk ==> Account.id
    // - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -

    @NotNull
    @JoinColumn(name = "account_fk", nullable = false)
    @ManyToOne
    public Account getAccountFk() {
        return accountFk;
    }

    /**
     * Set the {@link #accountFk} without adding this Device instance on the passed {@link #accountFk}
     */
    public void setAccountFk(Account accountFk) {
        this.accountFk = accountFk;
    }

    public Device accountFk(Account accountFk) {
        setAccountFk(accountFk);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Device withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Device && hashCode() == other.hashCode());
    }

    private IdentifiableHashBuilder identifiableHashBuilder = new IdentifiableHashBuilder();

    @Override
    public int hashCode() {
        return identifiableHashBuilder.hash(log, this);
    }

    /**
     * Construct a readable string representation for this Device instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("description", getDescription()) //
                .add("heightAboveSeaLevel", getHeightAboveSeaLevel()) //
                .add("lat", getLat()) //
                .add("longitue", getLongitue()) //
                .add("name", getName()) //
                .toString();
    }
}