//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/app.module.ts.p.vm
//
import { NgModule }       from '@angular/core';
import { BrowserModule  } from '@angular/platform-browser';
import { FormsModule }    from '@angular/forms';
import { HttpModule  }    from '@angular/http';
import { RouterModule  }  from '@angular/router';
import { ConfirmDialogModule, FileUploadModule, PanelModule, GrowlModule, MenubarModule, DialogModule, ButtonModule, AutoCompleteModule, DataTableModule, SharedModule, DropdownModule,PickListModule,CheckboxModule,TriStateCheckboxModule, InputTextModule,InputTextareaModule,CalendarModule,PasswordModule,TabViewModule } from 'primeng/primeng';
import { ConfirmationService } from 'primeng/primeng';
import { AppComponent }   from './app.component';
import { HomeComponent }  from './home.component';
import { MessageService } from './service/message.service';
import { routing }        from './app.routes';
import { EmailValidator } from './support/email.validator';

import { AuthorService } from './entities/author/author.service';
import { AuthorListComponent } from './entities/author/author-list.component';
import { AuthorDetailComponent } from './entities/author/author-detail.component';
import { AuthorLineComponent } from './entities/author/author-line.component';
import { AuthorCompleteComponent } from './entities/author/author-auto-complete.component';

import { BookService } from './entities/book/book.service';
import { BookListComponent } from './entities/book/book-list.component';
import { BookDetailComponent } from './entities/book/book-detail.component';
import { BookLineComponent } from './entities/book/book-line.component';
import { BookCompleteComponent } from './entities/book/book-auto-complete.component';

import { ProjectService } from './entities/project/project.service';
import { ProjectListComponent } from './entities/project/project-list.component';
import { ProjectDetailComponent } from './entities/project/project-detail.component';
import { ProjectLineComponent } from './entities/project/project-line.component';
import { ProjectCompleteComponent } from './entities/project/project-auto-complete.component';

import { RoleService } from './entities/role/role.service';
import { RoleListComponent } from './entities/role/role-list.component';
import { RoleDetailComponent } from './entities/role/role-detail.component';
import { RoleLineComponent } from './entities/role/role-line.component';
import { RoleCompleteComponent } from './entities/role/role-auto-complete.component';

import { UserService } from './entities/user/user.service';
import { UserListComponent } from './entities/user/user-list.component';
import { UserDetailComponent } from './entities/user/user-detail.component';
import { UserLineComponent } from './entities/user/user-line.component';
import { UserCompleteComponent } from './entities/user/user-auto-complete.component';

@NgModule({
    imports: [
// angular
        BrowserModule,
        FormsModule,
        HttpModule,
// primeng
        ConfirmDialogModule,
        FileUploadModule,
        PanelModule,
        GrowlModule,
        MenubarModule,
        DialogModule,
        ButtonModule,
        AutoCompleteModule,
        DataTableModule,
        SharedModule,
        DropdownModule,
        PickListModule,
        CheckboxModule,
        TriStateCheckboxModule,
        InputTextModule,
        InputTextareaModule,
        CalendarModule,
        PasswordModule,
        TabViewModule,
// our app
        routing
    ],
    declarations: [
        AppComponent,
        HomeComponent,
        EmailValidator
        ,
        AuthorListComponent,
        AuthorDetailComponent,
        AuthorLineComponent,
        AuthorCompleteComponent
        ,
        BookListComponent,
        BookDetailComponent,
        BookLineComponent,
        BookCompleteComponent
        ,
        ProjectListComponent,
        ProjectDetailComponent,
        ProjectLineComponent,
        ProjectCompleteComponent
        ,
        RoleListComponent,
        RoleDetailComponent,
        RoleLineComponent,
        RoleCompleteComponent
        ,
        UserListComponent,
        UserDetailComponent,
        UserLineComponent,
        UserCompleteComponent
    ],
    providers: [
        AuthorService,
        BookService,
        ProjectService,
        RoleService,
        UserService,
        MessageService,
        ConfirmationService
    ],
    bootstrap: [ AppComponent ]
})
export class AppModule {}
