//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/home.component.ts.p.vm
//
import { Component } from '@angular/core';

@Component({
    moduleId: module.id,
    templateUrl: 'home.component.html',
    styles: [`
             h3 {color: blue;}
             h4 {color: green;}
             .ui-g {
                text-align: center;
                background-color: aliceblue;}
             `]
})
export class HomeComponent {
}
