$output.webapp("app/app.component.ts")##
import { Component } from '@angular/core';
import { Routes, ROUTER_DIRECTIVES, ROUTER_PROVIDERS } from '@angular/router';
import {Menubar} from 'primeng/primeng';

#foreach($entity in $project.withoutManyToManyJoinEntities.list)
import { ${entity.service.type} } from './entities/${entity.model.var}/${entity.model.var}.service';
import { ${entity.model.type}ListComponent } from './entities/${entity.model.var}/${entity.model.var}-list.component';
import { ${entity.model.type}DetailComponent } from './entities/${entity.model.var}/${entity.model.var}-detail.component';
#end

@Component({
    selector: 'my-app',
    template: `
    <p-menubar>
     <ul>
         <li><a href="/"><span>Home</span></a>
         <li><a data-icon="fa-search"><span>Entities</span></a>
             <ul>
#foreach($entity in $project.withoutManyToManyJoinEntities.list)
                <li><a [routerLink]="['/${entity.model.var}list']"><span>${entity.model.type} List</span></a></li>
#end
             </ul>
         </li>
         <li><a data-icon="fa-gear" href="/swagger-ui.html">Swagger</a></li>
         <li><a data-icon="fa-question"><span>Documentation</span></a>
             <ul>
                <li><a href="https://github.com/jaxio/celerio-angular-quickstart">Source code on github for this project</a></li>
                <li><a href="http://www.jaxio.com/documentation/celerio/">Celerio Documentation</a></li>
                <li><a href="http://www.primefaces.org/primeng">PrimeNG Showcase</a></li>
                <li><a href="http://angular.io/">Angular 2</a></li>
                <li><a href="http://projects.spring.io/spring-boot/">Spring Boot</a></li>
             </ul>
         </li>
     </ul>
    </p-menubar>
    <router-outlet>
    <h1>{{title}}</h1>
    <p></p>
    </router-outlet>
  `,
    directives: [
        ROUTER_DIRECTIVES, Menubar
#foreach($entity in $project.withoutManyToManyJoinEntities.list)
        , ${entity.model.type}ListComponent, ${entity.model.type}DetailComponent
#end
    ],
    providers: [
        ROUTER_PROVIDERS
#foreach($entity in $project.withoutManyToManyJoinEntities.list)
        , ${entity.service.type}
#end
    ]
})
@Routes([
#foreach($entity in $project.withoutManyToManyJoinEntities.list)
#if($velocityCount > 1)
    ,
#end
    { path: '/${entity.model.var}list', component: ${entity.model.type}ListComponent },
    { path: '/${entity.model.var}/:id', component: ${entity.model.type}DetailComponent }
#end
])
export class AppComponent {
    title = 'Tour of Entities: generated by Celerio. Uses Angular2/PrimeNG/Spring';
}
