//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {Author} from '../author/author';

export class Book {
    // Raw attributes
    id : number;
    title : string;
    summary : string;
    extractFileName : string;
    extractContentType : string;
    extractSize : number;
    publicationDate : Date;
    bestSeller : boolean;
    price : number;
    // x-to-one
    author : Author;
    coAuthor : Author;
}
