//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent, ConfirmDialogModule, ConfirmationService } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { Book } from './book';
import { BookDetailComponent } from './book-detail.component';
import { BookService } from './book.service';
import { Author } from '../author/author';
import { AuthorLineComponent } from '../author/author-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'book-list.component.html',
	selector: 'book-list'
})
export class BookListComponent {

    @Input() header = "Books...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    bookToDelete : Book;

    // basic search criterias (visible if not in 'sub' mode)
    example : Book = new Book();

    // list is paginated
    currentPage : PageResponse<Book> = new PageResponse<Book>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _author : Author;
    private _coAuthor : Author;

    constructor(private router : Router,
        private bookService : BookService,
        private messageService : MessageService,
        private confirmationService: ConfirmationService) {
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.bookService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set author(author : Author) {
        if (author == null) {
            return;
        }
        this._author = author;

        this.example = new Book();
        this.example.author = new Author();
        this.example.author.id = this._author.id;
    }

    @Input()
    set coAuthor(coAuthor : Author) {
        if (coAuthor == null) {
            return;
        }
        this._coAuthor = coAuthor;

        this.example = new Book();
        this.example.coAuthor = new Author();
        this.example.coAuthor.id = this._coAuthor.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/book', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/book', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let bookToDelete : Book = <Book> rowData;

        this.confirmationService.confirm({
            message: 'Do you want to delete this record?',
            header: 'Delete Confirmation',
            icon: 'fa fa-trash',
            accept: () => {
                this.delete(bookToDelete);
            }
        });
    }

    private delete(bookToDelete : Book) {
        let id =  bookToDelete.id;

        this.bookService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(bookToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}