//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {AlarmReading} from './alarmReading';

@Component({
	template: `
        {{ alarmReading?.dateRecorded }} 	`,
	selector: 'alarmReading-line',
})
export class AlarmReadingLineComponent {
    @Input() alarmReading : AlarmReading;
}
