//
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { AlarmReading } from './alarmReading';
import { environment } from '../../../environments/environment';

@Injectable()
export class AlarmReadingService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a AlarmReading by id.
     */
    getAlarmReading(id : any) : Observable<AlarmReading> {
        return this.http.get(environment.url+'/api/alarmReadings/' + id)
            .map(response => new AlarmReading(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed alarmReading.
     */
    update(alarmReading : AlarmReading) : Observable<AlarmReading> {
        let body = JSON.stringify(alarmReading);

        return this.http.put(environment.url+'/api/alarmReadings/', body, this.options)
            .map(response => new AlarmReading(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of AlarmReading using the passed
     * alarmReading as an example for the search by example facility.
     */
    getPage(alarmReading : AlarmReading, event : LazyLoadEvent) : Observable<PageResponse<AlarmReading>> {
        let req = new PageRequestByExample(alarmReading, event);
        let body = JSON.stringify(req);

        return this.http.post(environment.url+'/api/alarmReadings/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<AlarmReading>(pr.totalPages, pr.totalElements, AlarmReading.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by AlarmReadingCompleteComponent.
     */
    complete(query : string) : Observable<AlarmReading[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post(environment.url+'/api/alarmReadings/complete', body, this.options)
            .map(response => AlarmReading.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an AlarmReading by id.
     */
    delete(id : any) {
        return this.http.delete(environment.url+'/api/alarmReadings/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
