//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {AlarmReading} from './alarmReading';
import {AlarmReadingService} from './alarmReading.service';
import {Device} from '../device/device';
import {AlarmRule} from '../alarmRule/alarmRule';

@Component({
    moduleId: module.id,
	templateUrl: 'alarmReading-detail.component.html',
	selector: 'alarmReading-detail',
})
export class AlarmReadingDetailComponent implements OnInit, OnDestroy {
    alarmReading : AlarmReading;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new AlarmReading
    set deviceFk(deviceFk : Device) {
        this.alarmReading = new AlarmReading();
        this.alarmReading.deviceFk = deviceFk;
    }

    @Input() // used to pass the parent when creating a new AlarmReading
    set ruleFk(ruleFk : AlarmRule) {
        this.alarmReading = new AlarmReading();
        this.alarmReading.ruleFk = ruleFk;
    }

    @Output() onSaveClicked = new EventEmitter<AlarmReading>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private alarmReadingService: AlarmReadingService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for alarmReading-detail ' + id);

            if (id === 'new') {
                this.alarmReading = new AlarmReading();
            } else {
                this.alarmReadingService.getAlarmReading(id)
                    .subscribe(alarmReading => {
                            this.alarmReading = alarmReading;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoDeviceFk() {
        this.router.navigate(['/device', this.alarmReading.deviceFk.id]);
    }

    clearDeviceFk() {
        this.alarmReading.deviceFk = null;
    }

    gotoRuleFk() {
        this.router.navigate(['/alarmRule', this.alarmReading.ruleFk.id]);
    }

    clearRuleFk() {
        this.alarmReading.ruleFk = null;
    }

    onSave() {
        this.alarmReadingService.update(this.alarmReading).
            subscribe(
                alarmReading => {
                    this.alarmReading = alarmReading;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.alarmReading);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
