//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, OnChanges, EventEmitter, SimpleChanges } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { MdDialog } from '@angular/material';
import { ConfirmDeleteDialogComponent } from "../../support/confirm-delete-dialog.component";
import { AlarmReading } from './alarmReading';
import { AlarmReadingDetailComponent } from './alarmReading-detail.component';
import { AlarmReadingService } from './alarmReading.service';
import { Device } from '../device/device';
import { DeviceLineComponent } from '../device/device-line.component';
import { AlarmRule } from '../alarmRule/alarmRule';
import { AlarmRuleLineComponent } from '../alarmRule/alarmRule-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'alarmReading-list.component.html',
	selector: 'alarmReading-list'
})
export class AlarmReadingListComponent {

    @Input() header = "AlarmReadings...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    alarmReadingToDelete : AlarmReading;

    // basic search criterias (visible if not in 'sub' mode)
    example : AlarmReading = new AlarmReading();

    // list is paginated
    currentPage : PageResponse<AlarmReading> = new PageResponse<AlarmReading>(0,0,[]);

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _deviceFk : Device;
    private _ruleFk : AlarmRule;

    constructor(private router : Router,
        private alarmReadingService : AlarmReadingService,
        private messageService : MessageService,
        private confirmDeleteDialog: MdDialog) {
    }

    /**
     * When used as a 'sub' component (to display one-to-many list), refreshes the table
     * content when the input changes.
     */
    ngOnChanges(changes: SimpleChanges) {
        this.loadPage({ first: 0, rows: 10, sortField: null, sortOrder: null, filters: null, multiSortMeta: null });
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.alarmReadingService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // X to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set deviceFk(deviceFk : Device) {
        if (deviceFk == null) {
            return;
        }
        this._deviceFk = deviceFk;

        this.example = new AlarmReading();
        this.example.deviceFk = new Device();
        this.example.deviceFk.id = this._deviceFk.id;
    }

    @Input()
    set ruleFk(ruleFk : AlarmRule) {
        if (ruleFk == null) {
            return;
        }
        this._ruleFk = ruleFk;

        this.example = new AlarmReading();
        this.example.ruleFk = new AlarmRule();
        this.example.ruleFk.id = this._ruleFk.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/alarmReading', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/alarmReading', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let alarmReadingToDelete : AlarmReading = <AlarmReading> rowData;

        let dialogRef = this.confirmDeleteDialog.open(ConfirmDeleteDialogComponent);
        dialogRef.afterClosed().subscribe(result => {
            if (result === 'delete') {
                this.delete(alarmReadingToDelete);
            }
        });
    }

    private delete(alarmReadingToDelete : AlarmReading) {
        let id =  alarmReadingToDelete.id;

        this.alarmReadingService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(alarmReadingToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}