//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {UseCase3Pk} from "./useCase3Pk";
import {UseCase2} from '../useCase2/useCase2';

export class UseCase3 {
    id : UseCase3Pk = new UseCase3Pk();
    // Raw attributes
    dummy : string;
    // x-to-one
    id2 : UseCase2;
}
