/*
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.mycompany.myapp.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.*;

import com.mycompany.myapp.domain.AlarmReading;
import com.mycompany.myapp.domain.AlarmReading_;

public interface AlarmReadingRepository extends JpaRepository<AlarmReading, Long> {

    default List<AlarmReading> complete(String query, int maxResults) {
        AlarmReading probe = new AlarmReading();

        ExampleMatcher matcher = ExampleMatcher.matching() //
        ;

        Page<AlarmReading> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}