//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/app.routes.ts.p.vm
//
import { ModuleWithProviders }  from '@angular/core';
import { Routes, RouterModule } from '@angular/router';

import { HomeComponent } from './home.component';

import { AccountListComponent } from './entities/account/account-list.component';
import { AccountDetailComponent } from './entities/account/account-detail.component';

import { AlarmReadingListComponent } from './entities/alarmReading/alarmReading-list.component';
import { AlarmReadingDetailComponent } from './entities/alarmReading/alarmReading-detail.component';

import { AlarmRuleListComponent } from './entities/alarmRule/alarmRule-list.component';
import { AlarmRuleDetailComponent } from './entities/alarmRule/alarmRule-detail.component';

import { DeviceListComponent } from './entities/device/device-list.component';
import { DeviceDetailComponent } from './entities/device/device-detail.component';

import { TempReadingListComponent } from './entities/tempReading/tempReading-list.component';
import { TempReadingDetailComponent } from './entities/tempReading/tempReading-detail.component';

export const routes: Routes = [
    { path : '',  component: HomeComponent }
    ,
    {path: 'account-list', component: AccountListComponent },
    {path: 'account/:id', component: AccountDetailComponent }
    ,
    {path: 'alarmReading-list', component: AlarmReadingListComponent },
    {path: 'alarmReading/:id', component: AlarmReadingDetailComponent }
    ,
    {path: 'alarmRule-list', component: AlarmRuleListComponent },
    {path: 'alarmRule/:id', component: AlarmRuleDetailComponent }
    ,
    {path: 'device-list', component: DeviceListComponent },
    {path: 'device/:id', component: DeviceDetailComponent }
    ,
    {path: 'tempReading-list', component: TempReadingListComponent },
    {path: 'tempReading/:id', component: TempReadingDetailComponent }
];

export const routing: ModuleWithProviders = RouterModule.forRoot(routes);
