//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/home.component.ts.p.vm
//
import { Component } from '@angular/core';

@Component({
    moduleId: module.id,
    templateUrl: 'home.component.html',
    styles: [`
             h1 {color: blue;}
             h4 {color: green;}
             .ui-g {
                text-align: center;
                background-color: aliceblue;}
             `]
})
export class HomeComponent {
}
