//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpClient, HttpResponse, HttpErrorResponse } from '@angular/common/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Role } from './role';
import { Observable } from 'rxjs/Rx';
import { catchError, map } from 'rxjs/operators';
import 'rxjs/add/observable/throw';

@Injectable()
export class RoleService {

    constructor(private http: HttpClient, private messageService : MessageService) {}

    /**
     * Get a Role by id.
     */
    getRole(id : any) : Observable<Role> {
        return this.http.get('/api/roles/' + id)
            .pipe(
                map(response => new Role(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Update the passed role.
     */
    update(role : Role) : Observable<Role> {
        let body = role;

        return this.http.put('/api/roles/', body)
            .pipe(
                map(response => new Role(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Load a page (for paginated datatable) of Role using the passed
     * role as an example for the search by example facility.
     */
    getPage(role : Role, event : LazyLoadEvent) : Observable<PageResponse<Role>> {
        let req = new PageRequestByExample(role, event);
        let body = req;

        return this.http.post<PageResponse<any>>('/api/roles/page', body)
            .pipe(
                map(pr =>  new PageResponse<Role>(pr.totalPages, pr.totalElements, Role.toArray(pr.content))),
                catchError(this.handleError)
            );
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by RoleCompleteComponent.
     */
    complete(query : string) : Observable<Role[]> {
        let body = {'query': query, 'maxResults': 10};
        return this.http.post<any[]>('/api/roles/complete', body)
            .pipe(
                map(response => Role.toArray(response)),
                catchError(this.handleError)
            );
    }

    /**
     * Delete an Role by id.
     */
    delete(id : any) {
        return this.http.delete('/api/roles/' + id)
            .pipe(catchError(this.handleError));
    }

    // sample method from angular doc
    private handleError (error: HttpErrorResponse) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message : 'Server error';
        console.error(errMsg);
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
