//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Role {
    // Raw attributes
    id : number;
    roleName : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.roleName = json.roleName;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Role[] {
        let roles : Role[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                roles.push(new Role(json));
            }
        }
        return roles;
    }
}
