//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class UseCase2 {
    // Raw attributes
    id : string;
    dummy : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.dummy = json.dummy;
        }
    }

    // Utils

    static toArray(jsons : any[]) : UseCase2[] {
        let useCase2s : UseCase2[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                useCase2s.push(new UseCase2(json));
            }
        }
        return useCase2s;
    }
}
