//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { UseCase2 } from './useCase2';

@Injectable()
export class UseCase2Service {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a UseCase2 by id.
     */
    getUseCase2(id : any) : Observable<UseCase2> {
        return this.http.get('/api/useCase2s/' + id)
            .map(response => new UseCase2(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed useCase2.
     */
    update(useCase2 : UseCase2) : Observable<UseCase2> {
        let body = JSON.stringify(useCase2);

        return this.http.put('/api/useCase2s/', body, this.options)
            .map(response => new UseCase2(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of UseCase2 using the passed
     * useCase2 as an example for the search by example facility.
     */
    getPage(useCase2 : UseCase2, event : LazyLoadEvent) : Observable<PageResponse<UseCase2>> {
        let req = new PageRequestByExample(useCase2, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/useCase2s/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<UseCase2>(pr.totalPages, pr.totalElements, UseCase2.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by UseCase2CompleteComponent.
     */
    complete(query : string) : Observable<UseCase2[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/useCase2s/complete', body, this.options)
            .map(response => UseCase2.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an UseCase2 by id.
     */
    delete(id : any) {
        return this.http.delete('/api/useCase2s/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
