//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity-line.component.ts.e.vm
//
import {Component, Input} from '@angular/core';
import {UseCase2} from './useCase2';

@Component({
	template: `
        {{ useCase2?.dummy }} 	`,
	selector: 'useCase2-line',
})
export class UseCase2LineComponent {
    @Input() useCase2 : UseCase2;
}
