//
// Project home: https://github.com/jaxio/celerio-angular-quickstart
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Source code: https://github.com/jaxio/celerio/
// Follow us on twitter: @jaxiosoft
// This header can be customized in Celerio conf...
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Author} from '../author/author';

export class Project {
    // Raw attributes
    id : number;
    name : string;
    url : string;
    openSource : boolean;
    // x-to-one
    author : Author;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.name = json.name;
            this.url = json.url;
            this.openSource = json.openSource;

            if (json.author != null) {
                this.author = new Author(json.author);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Project[] {
        let projects : Project[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                projects.push(new Project(json));
            }
        }
        return projects;
    }
}
