//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {Device} from '../device/device';

export class TempReading {
    // Raw attributes
    id : number;
    dateRecorded : Date;
    reading : number;
    tempType : string;
    // x-to-one
    deviceFk : Device;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            if (json.dateRecorded != null) {
                this.dateRecorded = new Date(json.dateRecorded);
            }
            this.reading = json.reading;
            this.tempType = json.tempType;

            if (json.deviceFk != null) {
                this.deviceFk = new Device(json.deviceFk);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : TempReading[] {
        let tempReadings : TempReading[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                tempReadings.push(new TempReading(json));
            }
        }
        return tempReadings;
    }
}
