//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { TempReading } from './tempReading';

@Injectable()
export class TempReadingService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a TempReading by id.
     */
    getTempReading(id : any) : Observable<TempReading> {
        return this.http.get('/api/tempReadings/' + id)
            .map(response => new TempReading(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed tempReading.
     */
    update(tempReading : TempReading) : Observable<TempReading> {
        let body = JSON.stringify(tempReading);

        return this.http.put('/api/tempReadings/', body, this.options)
            .map(response => new TempReading(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of TempReading using the passed
     * tempReading as an example for the search by example facility.
     */
    getPage(tempReading : TempReading, event : LazyLoadEvent) : Observable<PageResponse<TempReading>> {
        let req = new PageRequestByExample(tempReading, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/tempReadings/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<TempReading>(pr.totalPages, pr.totalElements, TempReading.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by TempReadingCompleteComponent.
     */
    complete(query : string) : Observable<TempReading[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/tempReadings/complete', body, this.options)
            .map(response => TempReading.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an TempReading by id.
     */
    delete(id : any) {
        return this.http.delete('/api/tempReadings/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
