//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity-detail.component.ts.e.vm
//
import {Component, OnInit, OnDestroy, Input, Output, EventEmitter} from '@angular/core';
import { Router, ActivatedRoute } from '@angular/router';
import { SelectItem } from 'primeng/primeng';
import { MessageService} from '../../service/message.service';
import {TempReading} from './tempReading';
import {TempReadingService} from './tempReading.service';
import {Device} from '../device/device';

@Component({
    moduleId: module.id,
	templateUrl: 'tempReading-detail.component.html',
	selector: 'tempReading-detail',
})
export class TempReadingDetailComponent implements OnInit, OnDestroy {
    tempReading : TempReading;

    private params_subscription: any;


    @Input() sub : boolean = false;
    @Input() // used to pass the parent when creating a new TempReading
    set deviceFk(deviceFk : Device) {
        this.tempReading = new TempReading();
        this.tempReading.deviceFk = deviceFk;
    }

    @Output() onSaveClicked = new EventEmitter<TempReading>();
    @Output() onCancelClicked = new EventEmitter();

    constructor(private route: ActivatedRoute, private router: Router, private messageService: MessageService, private tempReadingService: TempReadingService) {
    }

    ngOnInit() {
        if (this.sub) {
            return;
        }

        this.params_subscription = this.route.params.subscribe(params => {
            let id = params['id'];
            console.log('ngOnInit for tempReading-detail ' + id);

            if (id === 'new') {
                this.tempReading = new TempReading();
            } else {
                this.tempReadingService.getTempReading(id)
                    .subscribe(tempReading => {
                            this.tempReading = tempReading;
                        },
                        error =>  this.messageService.error('ngOnInit error', error)
                    );
            }
        });
    }

    ngOnDestroy() {
        if (!this.sub) {
            this.params_subscription.unsubscribe();
        }
    }

    gotoDeviceFk() {
        this.router.navigate(['/device', this.tempReading.deviceFk.id]);
    }

    clearDeviceFk() {
        this.tempReading.deviceFk = null;
    }

    onSave() {
        this.tempReadingService.update(this.tempReading).
            subscribe(
                tempReading => {
                    this.tempReading = tempReading;
                    if (this.sub) {
                        this.onSaveClicked.emit(this.tempReading);
                        this.messageService.info('Saved OK and msg emitted', 'Angular Rocks!')
                    } else {
                        this.messageService.info('Saved OK', 'Angular Rocks!')
                    }
                },
                error =>  this.messageService.error('Could not save', error)
            );
    }

    onCancel() {
        if (this.sub) {
            this.onCancelClicked.emit("cancel");
            this.messageService.info('Cancel clicked and msg emitted', 'Angular Rocks!')
        }
    }

}
