//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//
import {User} from '../user/user';

export class Passport {
    // Raw attributes
    id : number;
    passportNumber : string;
    expirationDate : Date;
    // x-to-one
    holder : User;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.passportNumber = json.passportNumber;
            if (json.expirationDate != null) {
                this.expirationDate = new Date(json.expirationDate);
            }

            if (json.holder != null) {
                this.holder = new User(json.holder);
            }
        }
    }

    // Utils

    static toArray(jsons : any[]) : Passport[] {
        let passports : Passport[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                passports.push(new Passport(json));
            }
        }
        return passports;
    }
}
