//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { Author } from './author';

@Injectable()
export class AuthorService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a Author by id.
     */
    getAuthor(id : any) : Observable<Author> {
        return this.http.get('/api/authors/' + id)
            .map(response => <Author> response.json())
            .catch(this.handleError);
    }

    /**
     * Update the passed author.
     */
    update(author : Author) : Observable<Author> {
        let body = JSON.stringify(author);

        return this.http.put('/api/authors/', body, this.options)
            .map(response => <Author> response.json())
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of Author using the passed
     * author as an example for the search by example facility.
     */
    getPage(author : Author, event : LazyLoadEvent) : Observable<PageResponse<Author>> {
        let req = new PageRequestByExample(author, event);
        let body = JSON.stringify(req);

        return this.http.post('/api/authors/page', body, this.options)
            .map(response => {
                let pr = <PageResponse<Author>> response.json();
                return new PageResponse<Author>(pr.totalPages, pr.totalElements, pr.content);
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by AuthorCompleteComponent.
     */
    complete(query : string) : Observable<Author[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post('/api/authors/complete', body, this.options)
            .map(response => <Author[]> response.json())
            .catch(this.handleError);
    }

    /**
     * Delete an Author by id.
     */
    delete(id : any) {
        return this.http.delete('/api/authors/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
