//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity-list.component.ts.e.vm
//
import { Component, Input, Output, EventEmitter } from '@angular/core';
import { Router } from '@angular/router';
import { DataTable, LazyLoadEvent, ConfirmDialogModule, ConfirmationService } from 'primeng/primeng';
import { PageResponse } from "../../support/paging";
import { MessageService } from '../../service/message.service';
import { Author } from './author';
import { AuthorDetailComponent } from './author-detail.component';
import { AuthorService } from './author.service';
import { AuthorLineComponent } from '../author/author-line.component';

@Component({
    moduleId: module.id,
	templateUrl: 'author-list.component.html',
	selector: 'author-list'
})
export class AuthorListComponent {

    @Input() header = "Authors...";

    // When 'sub' is true, it means this list is used as a one-to-many list.
    // It belongs to a parent entity, as a result the addNew operation
    // must prefill the parent entity. The prefill is not done here, instead we
    // emit an event.
    // When 'sub' is false, we display basic search criterias
    @Input() sub : boolean;
    @Output() onAddNewClicked = new EventEmitter();

    authorToDelete : Author;

    // basic search criterias (visible if not in 'sub' mode)
    example : Author = new Author();

    // list is paginated
    currentPage : PageResponse<Author> = new PageResponse<Author>(0,0,[]);

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    private _favoriteAuthor : Author;

    constructor(private router : Router,
        private authorService : AuthorService,
        private messageService : MessageService,
        private confirmationService: ConfirmationService) {
    }

    /**
     * Invoked when user presses the search button.
     */
    search(dt : DataTable) {
        if (!this.sub) {
            dt.reset();
            this.loadPage({ first: 0, rows: dt.rows, sortField: dt.sortField, sortOrder: dt.sortOrder, filters: null, multiSortMeta: dt.multiSortMeta });
        }
    }

    /**
     * Invoked automatically by primeng datatable.
     */
    loadPage(event : LazyLoadEvent) {
        this.authorService.getPage(this.example, event).
            subscribe(
                pageResponse => this.currentPage = pageResponse,
                error => this.messageService.error('Could not get the results', error)
            );
    }

    // Many to one: input param is used to filter the list when displayed
    // as a one-to-many list by the other side.
    @Input()
    set favoriteAuthor(favoriteAuthor : Author) {
        if (favoriteAuthor == null) {
            return;
        }
        this._favoriteAuthor = favoriteAuthor;

        this.example = new Author();
        this.example.favoriteAuthor = new Author();
        this.example.favoriteAuthor.id = this._favoriteAuthor.id;
    }


    onRowSelect(event : any) {
        let id =  event.data.id;
        this.router.navigate(['/author', id]);
    }

    addNew() {
        if (this.sub) {
            this.onAddNewClicked.emit("addNew");
        } else {
            this.router.navigate(['/author', 'new']);
        }
    }

    showDeleteDialog(rowData : any) {
        let authorToDelete : Author = <Author> rowData;

        this.confirmationService.confirm({
            message: 'Do you want to delete this record?',
            header: 'Delete Confirmation',
            icon: 'fa fa-trash',
            accept: () => {
                this.delete(authorToDelete);
            }
        });
    }

    private delete(authorToDelete : Author) {
        let id =  authorToDelete.id;

        this.authorService.delete(id).
            subscribe(
                response => {
                    this.currentPage.remove(authorToDelete);
                    this.messageService.info('Deleted OK', 'Angular Rocks!');
                },
                error => this.messageService.error('Could not delete!', error)
            );
    }
}