//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//

export class Author {
    // Raw attributes
    id : number;
    civility : string;
    firstName : string;
    lastName : string;
    email : string;
    birthDate : Date;
    birthDateTime : Date;
    // x-to-one
    favoriteAuthor : Author;
}
