//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {UseCase1Pk} from "./useCase1Pk";

export class UseCase1 {
    id : UseCase1Pk = new UseCase1Pk();
    // Raw attributes
    dummy : string;
}
