/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.time.Instant;
import java.time.LocalDate;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Author.class)
public abstract class Author_ {

    // Raw attributes
    public static volatile SingularAttribute<Author, Integer> id;
    public static volatile SingularAttribute<Author, Civility> civility;
    public static volatile SingularAttribute<Author, String> lastName;
    public static volatile SingularAttribute<Author, String> firstName;
    public static volatile SingularAttribute<Author, String> email;
    public static volatile SingularAttribute<Author, LocalDate> birthDate;
    public static volatile SingularAttribute<Author, Instant> birthDateTime;

    // Many to one
    public static volatile SingularAttribute<Author, Author> favoriteAuthor;

    // One to many
    public static volatile ListAttribute<Author, Book> books;
    public static volatile ListAttribute<Author, Project> projects;
}