/*
 * Project home: https://github.com/jaxio/celerio-angular-quickstart
 * 
 * Source code generated by Celerio, an Open Source code generator by Jaxio.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Source code: https://github.com/jaxio/celerio/
 * Follow us on twitter: @jaxiosoft
 * This header can be customized in Celerio conf...
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import java.time.LocalDate;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Passport.class)
public abstract class Passport_ {

    // Raw attributes
    public static volatile SingularAttribute<Passport, Integer> id;
    public static volatile SingularAttribute<Passport, String> passportNumber;
    public static volatile SingularAttribute<Passport, LocalDate> expirationDate;

    // One to one
    public static volatile SingularAttribute<Passport, User> holder;
}