/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Project.class)
public abstract class Project_ {

    // Raw attributes
    public static volatile SingularAttribute<Project, Integer> id;
    public static volatile SingularAttribute<Project, String> name;
    public static volatile SingularAttribute<Project, String> url;
    public static volatile SingularAttribute<Project, Boolean> openSource;

    // Many to one
    public static volatile SingularAttribute<Project, Author> author;
}