/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import javax.persistence.metamodel.ListAttribute;
import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(UseCase2.class)
public abstract class UseCase2_ {

    // Raw attributes
    public static volatile SingularAttribute<UseCase2, String> id;
    public static volatile SingularAttribute<UseCase2, String> dummy;

    // One to many
    public static volatile ListAttribute<UseCase2, UseCase3> useCase3s;
}