/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.mycompany.myapp.domain;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(UseCase1.class)
public abstract class UseCase1_ {
    // Composite primary key
    public static volatile SingularAttribute<UseCase1, UseCase1Pk> id;

    // Raw attributes
    public static volatile SingularAttribute<UseCase1, String> dummy;
}