//
//
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity.service.ts.e.vm
//
import { Injectable } from '@angular/core';
import { HttpModule, Http, Response, Headers, RequestOptions } from '@angular/http';
import { LazyLoadEvent } from 'primeng/primeng';
import { Observable } from 'rxjs/Observable';
import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/map';
import { MessageService } from '../../service/message.service';
import { PageResponse, PageRequestByExample } from '../../support/paging';
import { AlarmRule } from './alarmRule';
import { environment } from '../../../environments/environment';

@Injectable()
export class AlarmRuleService {

    private options = new RequestOptions({ headers: new Headers({ 'Content-Type': 'application/json' }) });

    constructor(private http: Http, private messageService : MessageService) {}

    /**
     * Get a AlarmRule by id.
     */
    getAlarmRule(id : any) : Observable<AlarmRule> {
        return this.http.get(environment.url+'/api/alarmRules/' + id)
            .map(response => new AlarmRule(response.json()))
            .catch(this.handleError);
    }

    /**
     * Update the passed alarmRule.
     */
    update(alarmRule : AlarmRule) : Observable<AlarmRule> {
        let body = JSON.stringify(alarmRule);

        return this.http.put(environment.url+'/api/alarmRules/', body, this.options)
            .map(response => new AlarmRule(response.json()))
            .catch(this.handleError);
    }

    /**
     * Load a page (for paginated datatable) of AlarmRule using the passed
     * alarmRule as an example for the search by example facility.
     */
    getPage(alarmRule : AlarmRule, event : LazyLoadEvent) : Observable<PageResponse<AlarmRule>> {
        let req = new PageRequestByExample(alarmRule, event);
        let body = JSON.stringify(req);

        return this.http.post(environment.url+'/api/alarmRules/page', body, this.options)
            .map(response => {
                let pr : any = response.json();
                return new PageResponse<AlarmRule>(pr.totalPages, pr.totalElements, AlarmRule.toArray(pr.content));
            })
            .catch(this.handleError);
    }

    /**
     * Performs a search by example on 1 attribute (defined on server side) and returns at most 10 results.
     * Used by AlarmRuleCompleteComponent.
     */
    complete(query : string) : Observable<AlarmRule[]> {
        let body = JSON.stringify({'query': query, 'maxResults': 10});
        return this.http.post(environment.url+'/api/alarmRules/complete', body, this.options)
            .map(response => AlarmRule.toArray(response.json()))
            .catch(this.handleError);
    }

    /**
     * Delete an AlarmRule by id.
     */
    delete(id : any) {
        return this.http.delete(environment.url+'/api/alarmRules/' + id).catch(this.handleError);
    }

    // sample method from angular doc
    private handleError (error: any) {
        // TODO: seems we cannot use messageService from here...
        let errMsg = (error.message) ? error.message :
        error.status ? `Status: ${error.status} - Text: ${error.statusText}` : 'Server error';
        console.error(errMsg); // log to console instead
        if (error.status === 401 ) {
            window.location.href = '/';
        }
        return Observable.throw(errMsg);
    }
}
