//
// Source code generated by Celerio, a Jaxio product.
// Documentation: http://www.jaxio.com/documentation/celerio/
// Follow us on twitter: @jaxiosoft
// Need commercial support ? Contact us: info@jaxio.com
// Template pack-angular:src/main/webapp/app/entities/entity.ts.e.vm
//
import {Author} from '../author/author';

export class Project {
    // Raw attributes
    id : number;
    name : string;
    url : string;
    openSource : boolean;
    // x-to-one
    author : Author;
}
