//
// 
// Source code generated by Celerio, an Open Source code generator by Jaxio.
// Template pack-angular:web/src/app/entities/entity.ts.e.vm
//

export class Account {
    // Raw attributes
    id : number;
    email : string;
    firstName : string;
    lastName : string;
    password : string;


    constructor(json? : any) {
        if (json != null) {
            this.id = json.id;
            this.email = json.email;
            this.firstName = json.firstName;
            this.lastName = json.lastName;
            this.password = json.password;
        }
    }

    // Utils

    static toArray(jsons : any[]) : Account[] {
        let accounts : Account[] = [];
        if (jsons != null) {
            for (let json of jsons) {
                accounts.push(new Account(json));
            }
        }
        return accounts;
    }
}
